// constants.js - Centralized game constants

export const PHYSICS = {
    GRAVITY: 0.6,
    FRICTION: 0.95,
    BOUNCE_DAMPING: 0.8,
    GOAL_WIDTH: 100,
    GOAL_HEIGHT: 120,
    WALL_BOUNCE: 0.8,
    CROSSBAR_BOUNCE: 0.7,
    CEILING_BOUNCE: 0.5,
    CROSSBAR_PUSH: 1.5,
    GROUND_FRICTION: 0.98,
    MIN_BOUNCE_VY: 1,
    SEPARATION_BUFFER: 2,
    MAX_PUSH_VELOCITY: 8,
    SIZE_DIFF_THRESHOLD: 0.15
};

export const AI_PARAMS = {
    DEFEND_DISTANCE: 200,
    ATTACK_DISTANCE: 250,
    INTERCEPT_DISTANCE: 200,
    BALL_SPEED_THRESHOLD: 3,
    MIDFIELD_COOLDOWN: 40,
    DEFEND_COOLDOWN: 20,
    ATTACK_COOLDOWN: 30,
    INTERCEPT_COOLDOWN: 15,
    BOSS_COOLDOWN: 5,
    GOAL_SAFETY_DISTANCE: 80,
    POSITIONING_THRESHOLD_BASE: 18,
    POSITIONING_THRESHOLD_RANGE: 15
};

export const MATCH = {
    DEFAULT_TIME_LIMIT: 120,
    DEFAULT_SCORE_TO_WIN: 5,
    COUNTDOWN_VALUE: 3,
    CELEBRATION_DURATION: 120,
    INTRO_PREVIEW_MS: 3000,
    INTRO_TEAMS_MS: 2000,
    INTRO_COUNTDOWN_MS: 3000,
    INTRO_GO_MS: 800,
    LOADING_DELAY_MS: 2500,
    QUICK_GOAL_THRESHOLD: 10,
    BLOWOUT_MARGIN: 5,
    COMEBACK_DEFICIT: 2
};

export const BALL = {
    DEFAULT_RADIUS: 15,
    TRAIL_SPEED_THRESHOLD: 15,
    HIGH_VELOCITY_THRESHOLD: 15
};

export const PLAYER = {
    SPEED_MULTIPLIER: 5,
    JUMP_MULTIPLIER: 15,
    KICK_POWER_MULTIPLIER: 10
};

export const NEAR_MISS = {
    COOLDOWN_MS: 2000,
    DISTANCE: 80,
    MIN_BALL_SPEED: 5
};

export const WEATHER = {
    NONE_CHANCE: 0.7,
    RAIN_FRICTION: 0.92,
    SNOW_FRICTION: 0.88,
    WIND_FORCE: 0.06
};
